//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emt7an
{
    using System;
    using System.Collections.Generic;
    
    public partial class USSER
    {
        public int US_ID { get; set; }
        public string US_NAME { get; set; }
        public string US_PASS { get; set; }
        public string US_GENDER { get; set; }
        public Nullable<int> US_AGE { get; set; }
        public string US_PHONENUM { get; set; }
        public string US_CITY { get; set; }
    }
}
